export declare const Layout = "MM/dd hh:mm:ssa 'yy -zzzz";
export declare const ANSIC = "Mon Jan _2 hh:mm:ss yyyy";
export declare const UnixDate = "Mon Jan _2 hh:mm:ss z yyyy";
export declare const RubyDate = "Mon Jan 02 hh:mm:ss z yyyy";
export declare const RFC822 = "dd Mon yy hh:mm z";
export declare const RFC822Z = "dd Mon yy hh:mm z";
export declare const RFC850 = "dddd, dd-Mon-yy hh:mm:ss z";
export declare const RFC1123 = "Mon, dd Mon yyyy hh:mm:ss z";
export declare const RFC1123Z = "Mon, dd Mon yyyy hh:mm:ss z";
export declare const RFC3339 = "yyyy-MM-ddTHH:mm:ssZ";
export declare const RFC3339Nano = "yyyy-MM-ddTHH:mm:ss.sssZ";
export declare const Kitchen = "h:mma";
export declare const Formats: {
    Layout: string;
    ANSIC: string;
    UnixDate: string;
    RubyDate: string;
    RFC822: string;
    RFC822Z: string;
    RFC850: string;
    RFC1123: string;
    RFC1123Z: string;
    RFC3339: string;
    RFC3339Nano: string;
    Kitchen: string;
};
export declare const Stamp = "MMM _d hh:mm:ss";
export declare const StampMilli = "MMM _d hh:mm:ss.sss";
export declare const StampMicro = "MMM _d hh:mm:ss.sss";
export declare const StampNano = "MMM _d hh:mm:ss.sss";
export declare const DateTime = "yyyy-MM-dd hh:mm:ss";
export declare const DateOnly = "yyyy-MM-dd";
export declare const TimeOnly = "hh:mm:ss";
export declare const Stamps: {
    Stamp: string;
    StampMilli: string;
    StampMicro: string;
    StampNano: string;
    DateTime: string;
    DateOnly: string;
    TimeOnly: string;
};
